### PR TITLE
Pull acrrued rewards figure from staking contract

### PR DESCRIPTION
**Pull request by tomhirst**
Playground to address: #253

### CODE REVIEW

**Comment by tomhirst** [comment]
I think the four columns on the account balance stats row works best. I reduced the text and icon sizes slightly to make it fit while still leaving enough room for padding.

I've added some call out text highlighting the % of all OGV locked up and the % vAPY users are receiving. I think this works quite well.

We also have a CTA (and the functionality) to call the `collectRewards()` function should a user have accrued any rewards.  

Here are a few screenshots showing the various states:

1 live stake but 0 rewards to collect
Screenshot 2022-07-18 at 17 47 38

1 live stake with accrued rewards to collect (ignore the 0 accrued rewards balance in the screenshot)
Screenshot 2022-07-18 at 17 47 15

0 live stakes but a non-zero OGV balance
Screenshot 2022-07-18 at 17 48 08

A non-zero OGV balance (ignore all balance figures)
Screenshot 2022-07-18 at 17 49 04

LMK what you think so far @micahalcorn

**Comment by micahalcorn** [comment]
> LMK what you think so far @micahalcorn


Nice, I agree that the four-column header works.

One might argue that the claim rewards function should be located near the rewards balance. I think it's fine for now down at the bottom. Just as a thought exercise, I was wondering what it would be like to have a button below every balance 🤔

|Balance|Staked|Vote Balance|Accrued Rewards|
|:---|:---|:---|:---|
|10,000|20,000|30,000|1,234|
|OGV|OGV|veOGV|OGV|
|~~~~~|~~~~~|~~~~~|~~~~~|
|**Buy**|**Stake**|**Unstake**|**Claim**|

Then you disable the buttons when they aren't actionable. Probably a dumb idea 🤷‍♂️

There's no scenario where you have zero staked and non-zero accrued rewards, correct? Because claiming is all or none and it's included in the unstake?

I think I'm okay with the "Buy OGV" CTA/button only being shown when the OGV balance and veOGV balance are both zero. There's always the nav link if someone wants it. We should pretty up that last screenshot though. I would maybe tone down the text and change it to something like "OGV is available on many of the top exchanges" followed by 3-4 logos and then the button linking to Uniswap.

**Comment by tomhirst** [comment]
> > LMK what you think so far @micahalcorn
> 
> Nice, I agree that the four-column header works.
> 
> One might argue that the claim rewards function should be located near the rewards balance. I think it's fine for now down at the bottom. Just as a thought exercise, I was wondering what it would be like to have a button below every balance 🤔
> 
> Balance	Staked	Vote Balance	Accrued Rewards
> 10,000	20,000	30,000	1,234
> OGV	OGV	veOGV	OGV
> ~~~~~	~~~~~	~~~~~	~~~~~
> **Buy**	**Stake**	**Unstake**	**Claim**
> Then you disable the buttons when they aren't actionable. Probably a dumb idea 🤷‍♂️
> 
> There's no scenario where you have zero staked and non-zero accrued rewards, correct? Because claiming is all or none and it's included in the unstake?
> 
> I think I'm okay with the "Buy OGV" CTA/button only being shown when the OGV balance and veOGV balance are both zero. There's always the nav link if someone wants it. We should pretty up that last screenshot though. I would maybe tone down the text and change it to something like "OGV is available on many of the top exchanges" followed by 3-4 logos and then the button linking to Uniswap.

I see where you're going with the buttons under each column. It would definitely indicate that the action is tied to the amounts in the cells above. My concern would be that in some cases it would be misleading though. For instance:

- Unstake under the Vote Balance amounts would infer every lockup would be unstaked by clicking that button
- Stake under the Staked OGV would infer that the totalled OGV already staked would be then staked again, not that it would take you to create a new stake

Correct. Unstaking calls collectRewards in an all-or-nothing fashion.

We can change the "You can buy..." message wording and tone down the size/weight. What logos would you like to be displayed above the button linking out to Uni? Assuming Huobi, and...

**Comment by tomhirst** [comment]
@micahalcorn Thanks!

Here's the updated screen, LMK if you're happy with this PR and we'll get it merged.

Screenshot 2022-07-21 at 15 01 03

**Comment by micahalcorn** [comment]
@tomhirst I think we should go ahead with these improvements, thanks. It would be nice to emphasize the APY more because it gets a little lost in the text. But we can continue to iterate after this is live in its current form.

**Review by micahalcorn — APPROVED** [review]

**Pull request merged**
