### PR TITLE
Theming

### PR DESCRIPTION
**Pull request by tomhirst**
Pretty beefy PR covering issue #38 that restyles in line with the Zeplin designs here: https://app.zeplin.io/project/5f28ed76ad0b5f20d672cde8/screen/6252ed8eab526c23b3d8c468

There's some styling and some component/layout refactoring in here to make the layout achievable and things more modular moving forward.

@micahalcorn I know you mentioned some things may be subject to change, so I'm happy to leave this open until we can finalise the things still being worked on in design. IE, I just saw the primary colour change from blue to green in Zeplin.

### CODE REVIEW

**Comment by tomhirst** [comment]
A few screenshots for reference:

Screenshot 2022-04-21 at 16 31 25

Screenshot 2022-04-21 at 16 31 34

Screenshot 2022-04-21 at 16 31 44

Screenshot 2022-04-21 at 16 31 55

**Review by sparrowDom — COMMENTED** [review]
Great job with this PR. I love how you organised the UI into reusable components and the code is very clean as well. 

There are some minor UI things we will need to address in the future. Mostly minor clipping things:
Screenshot 2022-04-21 at 19 09 00
Screenshot 2022-04-21 at 19 08 51

Screenshot 2022-04-21 at 19 10 53

Will let @tomlinton also comment since he sort of carries this project. My vote would be to merge this in and do any additional work from that point forward.

**Comment by tomlinton** [comment]
This is beautiful work @tomhirst, you really hit it out of the park. Appreciate the cleanup you've done and the extra component abstractions.

Per @sparrowDom we should merge this and resolve any little bits that crop up. Some of the stuff that turns up in testing will never happen in reality, e.g. no one will ever have 1B OGV (I hope 🤣).

**Review by tomlinton — APPROVED** [review]

**Comment by micahalcorn** [comment]
> Some of the stuff that turns up in testing will never happen in reality, e.g. no one will ever have 1B OGV (I hope 🤣).

Hostile takeover by Elon? 🚀

**Comment by tomhirst** [comment]
Thanks for the kind words @sparrowDom, @tomlinton!

Agreed on merging now. Can look at the overlapping elements and colours in new, smaller, PRs.

@micahalcorn Let's hope we don't have to "poison pill" to dilute him! 😆 

Cheers for reviewing 🤝

**Pull request merged**
