### PR TITLE
Deploy 014 - xOGN Governance

### PR DESCRIPTION
**Pull request by shahthepro**
### Addresses
|Contract|Address|
|-|-|
| Governance | [0x1D3Fbd4d129Ddd2372EA85c5Fa00b2682081c9EC](https://etherscan.io/address/0x1D3Fbd4d129Ddd2372EA85c5Fa00b2682081c9EC) |

### Parameteres
| Name | Value |
|-|-|
| Initial Vote Delay | 7200 blocks (~1d) |
| Voting Period | 14416 blocks (~2d) |
| Proposal Threshold | 100k xOGN |
| Late Quorum Extension | 7200 blocks (~1d) |

-----------

If you made a contract change, make sure to complete the checklist below before merging it in master.

Contract change checklist:
  - [ ] Code reviewed by 2 reviewers. 
  - [ ] Copy & paste code review [security checklist](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review-Example.md) below this checklist.
  - [ ] Unit tests pass
  - [ ] Slither tests pass with no warning
  - [ ] Echidna tests pass if PR includes changes to OUSD contract (not automated, run manually on local)

### CODE REVIEW

**Review by DanielVF — APPROVED** [review]
- [x] All deployed contracts are listed in the deploy PR's description
- [x] Deployed contract's verified code (and all dependencies) match the code in master
- [x] The transactions that interacted with the newly deployed contract match the deploy script.

**Comment by sparrowDom** [comment]
I've verified that: 
- [x] deployed xOGN contract's source matches the one in master
- [x] governance proposal's transactions match the ones in migration script 14

@shahthepro do you know why the new xOGN contract is not in `build/deployments/1/` folder?

**Comment by shahthepro** [comment]
> @shahthepro do you know why the new xOGN contract is not in `build/deployments/1/` folder?

It's not a new Contract. It's the same Governance contract that we used for OGV

**Comment by sparrowDom** [comment]
Oh got it thanks

**Pull request merged**
