### PR TITLE
Deploy 01 - Update Governance Parameters 

### PR DESCRIPTION
**Pull request by DanielVF**
Deploy for #328 Update Governance Parameters 

Contracts deployed:

  - Governance: [0x3cdD07c16614059e66344a7b579DAB4f9516C0b6](https://etherscan.io/address/0x3cdD07c16614059e66344a7b579DAB4f9516C0b6)
  - Timelock: [0x35918cDE7233F2dD33fA41ae3Cb6aE0e42E0e69F](https://etherscan.io/address/0x35918cDE7233F2dD33fA41ae3Cb6aE0e42E0e69F)

Governance proposal:

- None

----

Please verify that:

- [ ] Deployed contract verified code (and dependancies) match the final PR commit's code
- [ ] Deploy script is correct. (🟣 _Deploy was script was created during deploy, rather than with the rest of the code._)
- [ ] The transactions that interacted with the newly deployed contract match the deploy script.
- [ ] Governance proposal matches the deploy script (_No gov proposal_)
- [ ] Smoke tests pass after fork test execution of the governance proposal

### CODE REVIEW

**Comment by shahthepro** [comment]
Items reviewed

- [x] Deployed contract verified code (and dependancies) match the final PR commit's code
- [x] Deploy script is correct. (🟣 _Deploy was script was created during deploy, rather than with the rest of the code._)
- [x] The transactions that interacted with the newly deployed contract match the deploy script.
- [x] Governance proposal matches the deploy script (_No gov proposal_)
- [ ] Smoke tests pass after fork test execution of the governance proposal

**Review by franckc — APPROVED** [review]
LGTM

Performed the following verifications:
 - [x] Governance contract. Use Etherscan "Read Contract" to validate the values of all the public fields:
     - name: "OUSD Governance"
     - lateQuorumVoteExtension: 11520 -> 2 days in blocks
     - proposalThreshold: 10000000000000000000000000 -> 10M veOGV
     - timelock: 0x35918cde7233f2dd33fa41ae3cb6ae0e42e0e69f -> Address of the deployed timelock contract_
     - token: 0x0c4576ca1c365868e162554af8e385dc3e7c66d9 -> Address of veOGV
     - quorumDenominator: 100
     - quorumNumerator: 20 -> 20%
     - quorumVotes: 1971431893776931939644327371 -> dynamic value. 20% of veOGV total supply
     - version: 1
     - votingDelay: 1 -> 1 block
     - votingPeriod: 17280 -> 3 days in block

  - [x] Timelock contract. Use Etherscan "Read Contract" to validate the values of all the public fields:
     - getMinDelay: 172800 -> 2 days
     - hasRole
        - (CANCELLER_ROLE, 0x3cdD07c16614059e66344a7b579DAB4f9516C0b6 = governance) -> true
        - (EXECUTOR_ROLE, 0x3cdD07c16614059e66344a7b579DAB4f9516C0b6 = governance) -> true
        - (PROPOSE_ROLE, 0x3cdD07c16614059e66344a7b579DAB4f9516C0b6 = governance) -> true
        - (TIMELOCK_ADMIN_ROLE, 0x69e078ebc4631e1947f0c38ef0357de7ed064644 = deployer) -> false
 - [x] Deployed contract verified code (and dependancies) match the final PR commit's code
 - [x] Deploy script is correct. (🟣 Deploy was script was created during deploy, rather than with the rest of the code.)
 - [x] The transactions that interacted with the newly deployed contract match the deploy script.
 - [x] Governance proposal matches the deploy script (No gov proposal)

I did NOT perform the fork tests:
 - [ ] Smoke tests pass after fork test execution of the governance proposal.

**Comment by franckc** [comment]
@sparrowDom Can you review as well? ty... :)

**Comment by sparrowDom** [comment]
LGTM

Have not ran smoke tests as we don't have them in this repo

- [x] Governance contract.Can confirm all the governor values and the proper roles on Timelock controller. 

FYI there is also a [default admin role](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControl.sol#L57) that some of the contracts utilise ([example](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/afb20119b33072da041c97ea717d3ce4417b5e01/contracts/token/ERC20/presets/ERC20PresetMinterPauser.sol#L39)) 

- [x] Timelock contract has correct roles
```
#canceler role Governor -> True
t.hasRole("0xfd643c72710c63c0180259aba6b2d05451e3591a24e58b62239378085726f783", "0x3cdD07c16614059e66344a7b579DAB4f9516C0b6")
#executor role Governor -> True
t.hasRole("0xd8aa0f3194971a2a116679f7c2090f6939c8d4e01a2a8d7e41d55e5351469e63", "0x3cdD07c16614059e66344a7b579DAB4f9516C0b6")
#proposer role Governor -> True
t.hasRole("0xb09aa5aeb3702cfd50b6b62bc4532604938f21248a27a1d5ca736082b6819cc1", "0x3cdD07c16614059e66344a7b579DAB4f9516C0b6")
#timelock admin Governor -> False
t.hasRole("0x5f58e3a2316349923ce3780f8d587db2d72378aed66a8261c916544fa6846ca5", "0x3cdD07c16614059e66344a7b579DAB4f9516C0b6")
#default admin role Governor -> False
t.hasRole("0x0000000000000000000000000000000000000000000000000000000000000000", "0x3cdD07c16614059e66344a7b579DAB4f9516C0b6")

#canceler role Deployer -> False
t.hasRole("0xfd643c72710c63c0180259aba6b2d05451e3591a24e58b62239378085726f783", "0x69e078EBc4631E1947F0c38Ef0357De7ED064644")
#executor role Deployer -> False
t.hasRole("0xd8aa0f3194971a2a116679f7c2090f6939c8d4e01a2a8d7e41d55e5351469e63", "0x69e078EBc4631E1947F0c38Ef0357De7ED064644")
#proposer role Deployer -> False
t.hasRole("0xb09aa5aeb3702cfd50b6b62bc4532604938f21248a27a1d5ca736082b6819cc1", "0x69e078EBc4631E1947F0c38Ef0357De7ED064644")
#timelock admin Deployer -> False
t.hasRole("0x5f58e3a2316349923ce3780f8d587db2d72378aed66a8261c916544fa6846ca5", "0x69e078EBc4631E1947F0c38Ef0357De7ED064644")
#default admin role Deployer -> False
t.hasRole("0x0000000000000000000000000000000000000000000000000000000000000000", "0x69e078EBc4631E1947F0c38Ef0357De7ED064644")
```

**Review by sparrowDom — APPROVED** [review]
LGTM

**Pull request merged**
