### PR TITLE
RewardSource deployment files

### PR DESCRIPTION
**Pull request by shahthepro**
Code #297 and governance action #339

Deployed contracts:

- Rewards Source Impl: `0xE82191eF8996852a802aaE509993770480F9CA2C`

Please verify that:

- [ ] Deployed contract verified code (and dependancies) match the final PR commit's code
- [ ] The transactions that interacted with the newly deployed contract match the deploy script.
- [ ] Governance proposal matches the deploy script (_Gov proposal will be manual here_)
- [ ] Basic fork tests work after execution of the governance actions

### CODE REVIEW

**Review by DanielVF — APPROVED** [review]
### Deploy checklist:

- [x] Deployed contract verified code (and dependancies) match the final PR commit's code
- [x] The transactions that interacted with the newly deployed contract match the deploy script.
- [ ] Governance proposal matches the deploy script (_Gov proposal will be manual here_)
- [x] Basic fork test of new functionality works after execution of the governance actions

### Notes

This PR adds the missing contract json file for the rewards proxy. This looks correct.

### Fork Test

```python
from world import *

BINANCE_OGV = "0x28c6c06298d514db089934071355e5743bf21d60"
VEOGV = "0x0C4576Ca1c365868E162554AF8e385dc3e7C66D9"
REWARDS = "0x7d82E86CF1496f9485a8ea04012afeb3C7489397"

NEW_IMPL = "0xE82191eF8996852a802aaE509993770480F9CA2C"

rewardsProxy = Contract.from_explorer(REWARDS, REWARDS)


stakingProxy = Contract.from_explorer(VEOGV,VEOGV)

staking = Contract.from_explorer(VEOGV)
ogv = Contract.from_explorer(staking.ogv())


print("BONUS OGV %s" %  c18(ogv.balanceOf(BINANCE_OGV)))


fraction = staking.balanceOf(GOV_MULTISIG) /  staking.totalSupply()
print("Test user ownership %f" % fraction)
print("Expected increase %s" % c18(ogv.balanceOf(BINANCE_OGV) * fraction))

ogv.transfer(rewardsProxy, ogv.balanceOf(BINANCE_OGV), {'from': BINANCE_OGV})


with TemporaryFork():
  print("With no upgrade")
  staking.collectRewards({'from': GOV_MULTISIG})
  print(c18(ogv.balanceOf(GOV_MULTISIG)))

with TemporaryFork():
  print("With upgrade")
  rewardsProxy.upgradeTo(NEW_IMPL, {'from': GOV_MULTISIG})
  rewardsProxy.claimGovernance({'from': GOV_MULTISIG})

  staking.collectRewards({'from': GOV_MULTISIG})
  print(c18(ogv.balanceOf(GOV_MULTISIG)))

```

**Comment by sparrowDom** [comment]
**Checklist:**
- [x] Deployed contract verified code (and dependancies) match the final PR commit's code
- [x] The transactions that interacted with the newly deployed contract match the deploy script.
- [ ] Governance proposal matches the deploy script (_Gov proposal will be manual here_)
- [X] Basic fork tests work after execution of the governance actions

**Fork test:**
```python
from world import *

BINANCE_OGV = "0x28c6c06298d514db089934071355e5743bf21d60"
VEOGV = "0x0C4576Ca1c365868E162554AF8e385dc3e7C66D9"
REWARDS = "0x7d82E86CF1496f9485a8ea04012afeb3C7489397"
NEW_IMPL = "0xE82191eF8996852a802aaE509993770480F9CA2C"
RANDOM_ACC = "0x5E687f547d26732A3F1213e1C31432C3EF6810bc"

rewardsProxy = Contract.from_explorer(REWARDS, REWARDS)
staking = Contract.from_explorer(VEOGV)
ogv = Contract.from_explorer(staking.ogv())

random_share = staking.balanceOf(RANDOM_ACC) /  staking.totalSupply()

print("Random acc ownership %f" % random_share)
# size of the rewards pot so random acc gets 100 OGV
normalized_pot = 100 * 1e18 / random_share
ogv.transfer(rewardsProxy, normalized_pot, {'from': BINANCE_OGV})

rewards_received_no_upgrade = 0
rewards_received_upgrade = 0
with TemporaryFork():
  print("With no upgrade")
  staking.collectRewards({'from': RANDOM_ACC})
  rewards_received_no_upgrade = ogv.balanceOf(RANDOM_ACC)

with TemporaryFork():
  print("With upgrade")
  rewardsProxy.claimGovernance({'from': GOV_MULTISIG})
  rewardsProxy.upgradeTo(NEW_IMPL, {'from': GOV_MULTISIG})

  staking.collectRewards({'from': RANDOM_ACC})
  rewards_received_upgrade = ogv.balanceOf(RANDOM_ACC)

print("Difference %f" % ((rewards_received_upgrade - rewards_received_no_upgrade) / 1e18))
```
// Prints out `Difference 100.014977`

Deployment functionality confirmed. There is though 1.5 basis point difference between the expected amount and the amount rewarded (see above). @DanielVF @shahthepro might that to do with inflation?

**Review by sparrowDom — APPROVED** [review]

**Comment by DanielVF** [comment]
@sparrowDom 

Some of the difference is to do with the code in the two blocks running at different times, and thus having different reward inflation. I controlled for this by doing this before the forks:

```
synctime = chain.time() + 200
```

and then doing this before the collect in each fork:

```
chain.mine(timestamp=synctime)
```

Once the times have been synced I've confirmed that the inflation amounts between the two situations are always precisely the same.

Between time sync and doing all math in the python side in int's, the unexpected difference is now starting down at the 1e11 place between the two numbers. The rewards/staking contract only works in 1e12 resolution on rewards. Interestingly enough, the tiny remaining difference can be either above or below, depending on if I collect rewards before sending the big amount.

**Comment by sparrowDom** [comment]
ahh interesting thanks, yeah that makes so much sense since the whole inflation logic is tied to current time. Thanks for explaining!

**Pull request merged**
